language: node_js
node_js:
  - "8"
dist: trusty
sudo: false

cache:
  directories:
    - node_modules

addons:
  chrome: stable

script:
  - ng lint
  # - npm run test:headless
  - ng build --prod
  # - xvfb-run npm run e2e

before_deploy:
  - pip install --user awscli

deploy:
  provider: script
  script: ~/.local/bin/aws s3 sync dist/rndvz-frontend s3://rndvz/ --region=us-east-2 --delete
  skip_cleanup: true
  on:
    branch: master
