# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2

defaults: &defaults
  working_directory: /tmp/rndvz-frontend
  docker:
    - image: circleci/node:8-browsers

jobs:
  build:
    <<: *defaults

    steps:
      # Checkout code from repository to working_directory
      - checkout

      # Restore cached dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      # Download dependencies
      - run: npm install

      # Cache dependencies
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      # Build project
      - run: npm run ng build --prod

      # Cache project for deployment
      - persist_to_workspace:
          root: ./
          paths:
            - dist

  deploy:
    <<: *defaults

    steps:
      # Restore cached project
      - attach_workspace:
          at: /tmp/rndvz-frontend/dist
      
      # Install AWS CLI
      - run: sudo apt-get -y -qq install awscli

      # Set signature version for S3 Auth
      - run: aws configure set default.s3.signature_version s3v4

      - run: ls -al /tmp/rndvz-frontend/dist/dist/rndvz-frontend

      - run: printenv | grep AWS

      # Deploy frontend to S3 (and delete previous version)
      - run: aws --region us-east-2 s3 sync /tmp/rndvz-frontend/dist/dist/rndvz-frontend/ s3://rndvz/ --delete --debug

workflows:
  version: 2

  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build